services:

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tourism
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tourism-network
    expose:
      - "3306"
    restart: always

  app:
    image: lenam0910/tourismisland:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tourism
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    volumes:
      - /home/ubuntu/uploads:/home/ubuntu/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tourism-network

networks:
  tourism-network:
    driver: bridge

volumes:
  db-data:
